version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rentcar
    #command: php artisan serve --host=0.0.0.0
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    links:
      - db

  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    links:
      - app
      
  db:
    #Postgre Service
     image: postgres:12.1-alpine
     container_name: db
     restart: unless-stopped
     tty: true
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=dbrentcar
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     volumes:
      - "./postgres:/var/lib/postgresql/data"
     networks:
       - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local